// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 2905fd8e181cd2f4083a615fa51f1913)
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
import type { WebSocketServer } from '@cloudflare/workers-types'

declare namespace Cloudflare {
  interface Env {
    WEBSOCKET_SERVER: DurableObjectNamespace<WebSocketServer>
  }
}
interface Env extends Cloudflare.Env {}
